services:
  db:
    image: postgres:17.0-alpine
    container_name: db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  front:
    build: ./front
    container_name: front
    volumes:
      - ./front:/app
      - front_data:/app/node_modules
    ports:
      - "5173:5173"
  server:
    build: ./server
    container_name: server
    volumes:
      - ./server:/app

volumes:
  db_data:
  front_data:
